# Bitcoin Price Prediction

In [1]:
import numpy as np
import pandas as pd
from sklearn import metrics
import seaborn as sns

In [2]:
train = pd.read_csv("TRAIN.csv")
test = pd.read_csv("TEST.csv")

In [3]:
train

Date     Open     High      Low    Close  Adj Close       Volume
0    2017-01-01   963.66  1003.08   958.70   998.33     998.33    147775008
1    2017-01-02   998.62  1031.39   996.70  1021.75    1021.75    222184992
2    2017-01-03  1021.60  1044.08  1021.60  1043.84    1043.84    185168000
3    2017-01-04  1044.40  1159.42  1044.40  1154.73    1154.73    344945984
4    2017-01-05  1156.73  1191.10   910.42  1013.38    1013.38    510199008
..          ...      ...      ...      ...      ...        ...          ...
895  2019-06-15  8689.75  8859.13  8618.40  8838.38    8838.38  18371033226
896  2019-06-16  8841.44  9335.87  8814.56  8994.49    8994.49  23348550310
897  2019-06-17  8988.92  9416.41  8988.92  9320.35    9320.35  15562951918
898  2019-06-18  9335.47  9348.37  9004.90  9081.76    9081.76  15848210535
899  2019-06-19  9078.73  9299.62  9070.40  9273.52    9273.52  15546809946

[900 rows x 7 columns]

In [4]:
test

Date      Open      High       Low
0    2019-06-20   9273.06   9594.42   9232.48
1    2019-06-21   9525.07  10144.56   9525.07
2    2019-06-22  10175.92  11157.35  10107.04
3    2019-06-23  10696.69  11246.14  10556.10
4    2019-06-24  10853.74  11065.90  10610.43
..          ...       ...       ...       ...
144  2019-11-11   9056.92   9081.28   8700.61
145  2019-11-12   8759.75   8853.77   8685.43
146  2019-11-13   8812.03   8836.84   8761.65
147  2019-11-14   8811.94   8826.94   8692.55
148  2019-11-15   8705.71   8730.87   8484.84

[149 rows x 4 columns]

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
train["Date"] = le.fit_transform(train["Date"])

In [6]:
train

Date     Open     High      Low    Close  Adj Close       Volume
0       0   963.66  1003.08   958.70   998.33     998.33    147775008
1       1   998.62  1031.39   996.70  1021.75    1021.75    222184992
2       2  1021.60  1044.08  1021.60  1043.84    1043.84    185168000
3       3  1044.40  1159.42  1044.40  1154.73    1154.73    344945984
4       4  1156.73  1191.10   910.42  1013.38    1013.38    510199008
..    ...      ...      ...      ...      ...        ...          ...
895   895  8689.75  8859.13  8618.40  8838.38    8838.38  18371033226
896   896  8841.44  9335.87  8814.56  8994.49    8994.49  23348550310
897   897  8988.92  9416.41  8988.92  9320.35    9320.35  15562951918
898   898  9335.47  9348.37  9004.90  9081.76    9081.76  15848210535
899   899  9078.73  9299.62  9070.40  9273.52    9273.52  15546809946

[900 rows x 7 columns]

In [7]:
train.drop(["Adj Close","Volume"],axis=1,inplace=True)

In [8]:
train

Date     Open     High      Low    Close
0       0   963.66  1003.08   958.70   998.33
1       1   998.62  1031.39   996.70  1021.75
2       2  1021.60  1044.08  1021.60  1043.84
3       3  1044.40  1159.42  1044.40  1154.73
4       4  1156.73  1191.10   910.42  1013.38
..    ...      ...      ...      ...      ...
895   895  8689.75  8859.13  8618.40  8838.38
896   896  8841.44  9335.87  8814.56  8994.49
897   897  8988.92  9416.41  8988.92  9320.35
898   898  9335.47  9348.37  9004.90  9081.76
899   899  9078.73  9299.62  9070.40  9273.52

[900 rows x 5 columns]

In [9]:
test["Date"] = le.fit_transform(test["Date"])

In [10]:
test

Date      Open      High       Low
0       0   9273.06   9594.42   9232.48
1       1   9525.07  10144.56   9525.07
2       2  10175.92  11157.35  10107.04
3       3  10696.69  11246.14  10556.10
4       4  10853.74  11065.90  10610.43
..    ...       ...       ...       ...
144   144   9056.92   9081.28   8700.61
145   145   8759.75   8853.77   8685.43
146   146   8812.03   8836.84   8761.65
147   147   8811.94   8826.94   8692.55
148   148   8705.71   8730.87   8484.84

[149 rows x 4 columns]

In [11]:
x = train.iloc[:,0:-1].values
y = train.iloc[:,-1].values

In [12]:
x

array([[0.00000e+00, 9.63660e+02, 1.00308e+03, 9.58700e+02],
       [1.00000e+00, 9.98620e+02, 1.03139e+03, 9.96700e+02],
       [2.00000e+00, 1.02160e+03, 1.04408e+03, 1.02160e+03],
       ...,
       [8.97000e+02, 8.98892e+03, 9.41641e+03, 8.98892e+03],
       [8.98000e+02, 9.33547e+03, 9.34837e+03, 9.00490e+03],
       [8.99000e+02, 9.07873e+03, 9.29962e+03, 9.07040e+03]])

In [13]:
y

array([  998.33,  1021.75,  1043.84,  1154.73,  1013.38,   902.2 ,
         908.59,   911.2 ,   902.83,   907.68,   777.76,   804.83,
         823.98,   818.41,   821.8 ,   831.53,   907.94,   886.62,
         899.07,   895.03,   921.79,   924.67,   921.01,   892.69,
         901.54,   917.59,   919.75,   921.59,   919.5 ,   920.38,
         970.4 ,   989.02,  1011.8 ,  1029.91,  1042.9 ,  1027.34,
        1038.15,  1061.35,  1063.07,   994.38,   988.67,  1004.45,
         999.18,   990.64,  1004.55,  1007.48,  1027.44,  1046.21,
        1054.42,  1047.87,  1079.98,  1115.3 ,  1117.44,  1166.72,
        1173.68,  1143.84,  1165.2 ,  1179.97,  1179.97,  1222.5 ,
        1251.01,  1274.99,  1255.15,  1267.12,  1272.83,  1223.54,
        1150.  ,  1188.49,  1116.72,  1175.83,  1221.38,  1231.92,
        1240.  ,  1249.61,  1187.81,  1100.23,   973.82,  1036.74,
        1054.23,  1120.54,  1049.14,  1038.59,   937.52,   972.78,
         966.72,  1045.77,  1047.15,  1039.97,  1026.43,  1071

In [14]:
y.shape

(900,)

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0)

In [16]:
x_train

array([[ 505.  , 8522.33, 8557.52, 8365.12],
       [ 210.  , 2724.39, 2758.53, 2644.85],
       [ 655.  , 6542.33, 6567.54, 6450.04],
       ...,
       [ 629.  , 6735.05, 6814.56, 6616.8 ],
       [ 559.  , 6247.5 , 6298.19, 6212.22],
       [ 684.  , 5645.32, 5657.02, 5498.94]])

In [17]:
x_train.shape

(675, 4)

In [18]:
x_test

array([[4.92000e+02, 9.38087e+03, 9.46275e+03, 9.12777e+03],
       [1.41000e+02, 2.04319e+03, 2.30390e+03, 2.01787e+03],
       [4.09000e+02, 8.59992e+03, 9.51854e+03, 8.59992e+03],
       [3.10000e+01, 9.70940e+02, 9.89110e+02, 9.70740e+02],
       [5.70000e+02, 8.37966e+03, 8.41687e+03, 8.08636e+03],
       [5.93000e+02, 6.34091e+03, 6.58250e+03, 6.32497e+03],
       [8.73000e+02, 7.88170e+03, 8.14072e+03, 7.82445e+03],
       [3.99000e+02, 9.17570e+03, 9.33487e+03, 8.03122e+03],
       [4.06000e+02, 8.61613e+03, 8.61613e+03, 7.93110e+03],
       [2.72000e+02, 4.16611e+03, 4.35843e+03, 4.16086e+03],
       [6.91000e+02, 4.36070e+03, 4.39642e+03, 4.19568e+03],
       [6.00000e+01, 1.22468e+03, 1.26213e+03, 1.21562e+03],
       [3.12000e+02, 7.44683e+03, 7.44683e+03, 7.10152e+03],
       [6.42000e+02, 6.57415e+03, 6.62362e+03, 6.55741e+03],
       [5.00000e+02, 8.50441e+03, 8.50843e+03, 8.17549e+03],
       [3.45000e+02, 1.69198e+04, 1.77818e+04, 1.65716e+04],
       [3.51000e+02, 1.9

In [19]:
x_test.shape

(225, 4)

In [20]:
y_train

array([ 8418.99,  2757.18,  6476.71,  1079.98,  6461.01,  6972.37,
        2511.81,  6544.43,  1490.09,  3630.68,  2655.88,  6635.75,
        8094.32,  5247.35,  5647.21,   777.76,  1182.94,  1116.72,
        4098.37, 10058.8 ,  3545.86, 11657.2 ,  4017.27, 11112.7 ,
        6285.99,  4030.85,  1043.84,  7927.71,  5096.59,  8230.92,
       12952.2 ,  3742.7 ,  5399.37,  5324.55, 10221.1 ,   921.79,
        3963.07,  7032.85,  6228.81,  1231.92,  1047.87,  7916.88,
       10233.6 ,  4163.07,  1317.73,   973.82,  1054.42,  6480.38,
        3631.04,  3820.41,  6734.95,  3857.72,  1272.83,  4134.44,
        1117.44, 15201.  ,  1555.45,  6568.23, 11916.7 ,  1321.79,
         823.98,  2732.16,  1723.35,  8913.47,  4334.68,  7023.52,
        4565.3 , 14156.4 ,  5904.83,  7204.77,  3521.06, 10551.8 ,
        8510.38,  3753.99,  7047.16,   886.62,  3601.01,  7621.3 ,
        4158.18, 14026.6 ,  4703.39,  6456.58,  2721.79,  2518.66,
        4029.33,  7954.48,  6153.85,  8043.95,  6968.32,  1054

In [21]:
y_train.shape

(675,)

In [22]:
y_test

array([ 9234.82,  2173.4 ,  9494.63,   989.02,  8181.39,  6580.63,
        7987.37,  8277.01,  8129.97,  4338.71,  4347.11,  1251.01,
        7143.58,  6622.48,  8368.83, 17415.4 , 19114.2 ,  6588.31,
        3653.53,  5795.71,   821.8 ,  3486.18,  3880.76,  3954.12,
        6906.92,  1167.54,  2805.62,  3998.98,  6853.84,  6597.55,
        2286.41,  7418.49,  3745.95,  8265.59,  6465.41,  7343.9 ,
       14656.2 , 11259.4 ,  5064.49,  6890.52,  6453.72,  4087.66,
        1175.95,  9373.01,  6517.31,  6529.59,  2754.86,  1143.84,
        1223.54,  4025.25,  6644.13,  1929.82,  7407.41,  6008.42,
        3894.13,  4370.81,  1036.74,  8145.86, 10931.4 ,  6308.53,
        8247.18,  3625.04,  5780.9 ,  3632.07,  2320.42,  6281.2 ,
        7624.92,  7707.77,  3620.81,  8895.58,  5572.36,  6543.2 ,
         902.83,  3648.43, 11490.5 ,  6773.88,  7814.92,  2304.98,
        2202.42,  7459.69, 11171.4 ,  4076.63,  6157.13,  1042.9 ,
        3903.94,  9348.48,  9273.52,  8041.78,   921.59,  7708

In [23]:
y_test.shape

(225,)

In [24]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

In [25]:
y_pred = reg.predict(test)

In [26]:
y_pred

array([ 9457.55125825, 10014.62792901, 10964.7855118 , 11026.55083475,
       10801.34097034, 11637.48269179, 13565.9094688 , 11719.95442327,
       12126.59397208, 11759.54912942, 11394.08094392, 10669.44093901,
       10299.85175734, 11800.44574752, 11417.15926895, 11080.19490814,
       11474.68014883, 11367.78771134, 12152.4636023 , 12596.08900088,
       12479.60331841, 11455.9282553 , 11659.52131344, 11199.17970343,
       10673.64049981, 10756.2776499 , 10051.07414839,  9664.9136517 ,
       10403.7748214 , 10359.02377923, 10870.575513  , 10503.30812494,
       10284.83997768,  9973.01031939,  9647.20315791, 10014.60927262,
        9700.07036836,  9787.55434861,  9334.97867535,  9531.70429789,
        9544.49829539,  9958.88678165, 10234.97180697, 10518.42757465,
       10806.95178514, 10771.25662546, 11736.62373785, 11830.80669014,
       11865.59131784, 11624.60854532, 11703.83663885, 11481.03066885,
       11337.56271457, 11287.85111445, 10981.87535648, 10283.8199918 ,
      

In [27]:
val = [[898,9335.47,9348.37,9004.90]]
pred = reg.predict(val)
print(pred)

[9087.06958382]


In [33]:
print('train accuracy: ', reg.score(x_train,y_train),'\ntest accuracy: ', reg.score(x_test,y_test) )

train accuracy:  0.9985614986209115 
test accuracy:  0.9988447917827912


In [30]:
Output = pd.DataFrame({"Date" : pd.read_csv("TEST.csv")["Date"], "Close" : y_pred})

In [31]:
Output

Date         Close
0    2019-06-20   9457.551258
1    2019-06-21  10014.627929
2    2019-06-22  10964.785512
3    2019-06-23  11026.550835
4    2019-06-24  10801.340970
..          ...           ...
144  2019-11-11   8784.795288
145  2019-11-12   8717.992934
146  2019-11-13   8717.273168
147  2019-11-14   8668.552752
148  2019-11-15   8515.435316

[149 rows x 2 columns]

In [34]:
Output.to_csv("output.csv", index=False)